
'use strict';
const $=id=>document.getElementById(id),format=new Intl.NumberFormat('en-NZ',{maximumFractionDigits:0});
const state={year:2035,mode:'soil',national:false,threeD:true,playing:false},qa={errors:[],mapReady:false,locatorReady:false,tileFailures:0};window.regroundQA=qa;
window.addEventListener('error',e=>qa.errors.push(e.message));
function model(year){const total=2000000*1.012**(year-2026),share=.01+.09*(year-2026)/9,reuse=total*share,bau=total*92*.105/1000,saved=reuse*80*.105/1000;return {total,share,reuse,landfill:total-reuse,bau,saved,withReGround:bau-saved,reduction:saved/bau*100};}
const maximum=model(2035);
function comparison(){const d=model(state.year);return state.mode==='soil'?{first:'Still to disposal',second:'Reused locally',a:d.landfill,b:d.reuse,max:maximum.total,unit:'tonnes / year',tag:'01 / Auckland soil scenario',title:'Most soil still takes the disposal route.',text:'ReGround’s scenario redirects suitable soil to nearby demand. Move the year to see reuse grow from 1% to 10%.',note:'Height = annual tonnes. Orange + blue = total soil.'}:state.mode==='distance'?{first:'Disposal route',second:'Local reuse route',a:92,b:12,max:92,unit:'km',tag:'02 / Transport assumptions',title:'A shorter journey changes the equation.',text:'The model compares a 92 km disposal journey with a 12 km local reuse journey — 80 km less for every tonne redirected.',note:'Height = assumed trip distance. These are route assumptions, not mapped journeys.'}:{first:'Business as usual',second:'With ReGround',a:d.bau,b:d.withReGround,max:maximum.bau,unit:'t CO₂-e / year',tag:'03 / Transport impact',title:'Less travel. Lower transport emissions.',text:'Compare all soil taking the disposal route with the ReGround scenario. The blue column includes both reuse and remaining disposal.',note:'Height = transport emissions. The difference is annual emissions avoided.'};}
function tileStyle(streets=true){return {version:8,sources:{nz:{type:'geojson',data:NZ},streets:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'water',type:'background',paint:{'background-color':'#dfe9e7'}},{id:'land',type:'fill',source:'nz',paint:{'fill-color':'#f6f5e9'}},{id:'coast',type:'line',source:'nz',paint:{'line-color':'#a9c1b6','line-width':1}},...(streets?[{id:'streets',type:'raster',source:'streets',paint:{'raster-opacity':.7}}]:[])]};}
let map,locator,popup,timer,ready=false,tileWarned=false,lastLayout='';
function layout(){const mobile=innerWidth<700,box=$('stage').getBoundingClientRect(),top=mobile?Math.ceil($('status').getBoundingClientRect().bottom-box.top+8):0,next=mobile?String(top):'desktop';$('map').style.top=top+'px';$('map').style.bottom=mobile?'140px':'0';$('stage').style.height=mobile?(top+605)+'px':'';map?.resize();locator?.resize();const changed=lastLayout!==next;lastLayout=next;return changed;}
const akl=[174.7633,-36.8485];
function columns(){const c=comparison(),width=state.national?.09:.01,gap=state.national?.15:.03,maxHeight=state.national?65000:6000;
return {type:'FeatureCollection',features:[{label:c.first,value:c.a,color:'#d56a36',lon:akl[0]-gap},{label:c.second,value:c.b,color:'#2d77ae',lon:akl[0]+gap}].map((r,i)=>{const lon=r.lon,lat=akl[1],w=width;return {type:'Feature',properties:{label:r.label,value:r.value,unit:c.unit,color:r.color,height:r.value/c.max*maxHeight,year:state.year,index:i},geometry:{type:'Polygon',coordinates:[[[lon-w,lat-w],[lon+w,lat-w],[lon+w,lat+w],[lon-w,lat+w],[lon-w,lat-w]]]}};})};}
function update(){const d=model(state.year),c=comparison();$('year').value=String(state.year);$('year').textContent=state.year;$('slider').value=state.year;$('slider').setAttribute('aria-valuetext',state.year+' scenario');$('modeTag').textContent=c.tag;$('storyTitle').textContent=c.title;$('storyText').textContent=c.text;$('firstLabel').textContent=c.first;$('secondLabel').textContent=c.second;$('firstValue').textContent=format.format(c.a)+(state.mode==='distance'?' km':'');$('secondValue').textContent=format.format(c.b)+(state.mode==='distance'?' km':'');$('legendnote').textContent=c.note+' Units: '+c.unit+'.';$('total').innerHTML=(d.total/1e6).toFixed(2)+' <span>million tonnes / year</span>';$('reuse').innerHTML=format.format(d.reuse)+' <span>tonnes / year</span>';$('saved').innerHTML=format.format(d.saved)+' <span>t CO₂-e / year</span>';$('share').textContent=(d.share*100).toFixed(0)+'% adoption in the '+state.year+' scenario';$('reduction').textContent=d.reduction.toFixed(1)+'% less than business-as-usual transport emissions';document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===state.mode)));if(ready){map.getSource('columns').setData(columns());if(popup)popup.remove();if(layout())camera();}}
function camera(){if(!ready)return;const mobile=innerWidth<700;map.flyTo(state.national?{center:[173.4,-40.5],zoom:mobile?3.4:4.3,bearing:0,pitch:state.threeD?35:0,padding:{top:0,bottom:85,left:mobile?0:180,right:0},duration:matchMedia('(prefers-reduced-motion: reduce)').matches?0:800}:{center:akl,zoom:mobile?10:10.3,bearing:-22,pitch:state.threeD?55:0,padding:{top:0,bottom:mobile?20:100,left:mobile?0:210,right:0},duration:matchMedia('(prefers-reduced-motion: reduce)').matches?0:800});}
function setNational(n){state.national=n;$('locatorButton').textContent=n?'Back to Auckland':'View New Zealand';$('national').setAttribute('aria-pressed',String(n));$('auckland').setAttribute('aria-pressed',String(!n));update();camera();}
function stop(){clearInterval(timer);state.playing=false;$('play').setAttribute('aria-pressed','false');$('play').textContent='Play';$('play').setAttribute('aria-label','Play annual scenario');}
$('slider').addEventListener('input',e=>{stop();state.year=+e.target.value;update();});document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{state.mode=b.dataset.mode;update();}));$('play').addEventListener('click',()=>{if(state.playing){stop();return;}state.playing=true;$('play').setAttribute('aria-pressed','true');if(state.year===2035){state.year=2026;update();}$('play').textContent='Pause';$('play').setAttribute('aria-label','Pause annual scenario');timer=setInterval(()=>{if(state.year>=2035){stop();return;}state.year++;update();},1000);});$('auckland').addEventListener('click',()=>setNational(false));$('national').addEventListener('click',()=>setNational(true));$('locatorButton').addEventListener('click',()=>setNational(!state.national));$('tilt').addEventListener('click',()=>{state.threeD=!state.threeD;$('tilt').setAttribute('aria-pressed',String(state.threeD));$('tilt').textContent=state.threeD?'3D view':'2D view';camera();});$('reset').addEventListener('click',()=>{stop();state.year=2035;state.mode='soil';state.threeD=true;$('tilt').textContent='3D view';$('tilt').setAttribute('aria-pressed','true');setNational(false);});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});window.addEventListener('resize',()=>{layout();camera();});
update();layout();
try{map=new maplibregl.Map({container:'map',style:tileStyle(),center:akl,zoom:10.3,pitch:55,bearing:-22,antialias:true,attributionControl:{compact:true},maxZoom:16,minZoom:3});map.addControl(new maplibregl.NavigationControl({visualizePitch:true}),'top-right');
map.on('load',()=>{map.addSource('columns',{type:'geojson',data:columns()});map.addLayer({id:'comparison-columns',type:'fill-extrusion',source:'columns',paint:{'fill-extrusion-color':['get','color'],'fill-extrusion-height':['get','height'],'fill-extrusion-base':0,'fill-extrusion-opacity':.94,'fill-extrusion-height-transition':{duration:450}}});map.addSource('anchor',{type:'geojson',data:{type:'Feature',properties:{},geometry:{type:'Point',coordinates:akl}}});map.addLayer({id:'auckland-anchor',type:'circle',source:'anchor',paint:{'circle-radius':5,'circle-color':'#19372f','circle-stroke-color':'white','circle-stroke-width':2}});ready=true;qa.mapReady=true;layout();camera();$('status').textContent=tileWarned?'Geographic outline loaded · street tiles unavailable':'Auckland aggregate · hover or click a column';map.on('mousemove','comparison-columns',e=>{map.getCanvas().style.cursor='pointer';if(!e.features?.length)return;const p=e.features[0].properties;if(popup)popup.remove();popup=new maplibregl.Popup({closeButton:false,closeOnClick:false}).setLngLat(e.lngLat).setHTML('<strong>'+p.label+'</strong><p>'+format.format(p.value)+' '+p.unit+'</p><p>'+p.year+' · Auckland-wide scenario</p>').addTo(map);});map.on('mouseleave','comparison-columns',()=>{map.getCanvas().style.cursor='';popup?.remove();});map.on('click','comparison-columns',e=>{if(!e.features?.length)return;const p=e.features[0].properties;popup?.remove();popup=new maplibregl.Popup().setLngLat(e.lngLat).setHTML('<strong>'+p.label+'</strong><p>'+format.format(p.value)+' '+p.unit+'</p><p>Auckland aggregate, '+p.year+'</p><p>Display anchor, not a project site.</p>').addTo(map);});});
map.on('error',e=>{if(e.sourceId==='streets'){qa.tileFailures++;tileWarned=true;$('status').textContent='Geographic outline loaded · street tiles unavailable';}else{qa.errors.push(e.error?.message||'Map error');}});
locator=new maplibregl.Map({container:'locator',style:tileStyle(false),center:[173,-41],zoom:3.1,interactive:false,attributionControl:false});locator.on('load',()=>{locator.fitBounds([[166.2,-47.5],[178.7,-34]],{padding:20,duration:0});new maplibregl.Marker({color:'#d56a36',scale:.5}).setLngLat(akl).addTo(locator);qa.locatorReady=true;});
}catch(e){qa.errors.push(e.message);$('stage').classList.add('error');$('status').textContent='Map unavailable · scenario figures remain active';}
window.regroundModel=model;window.regroundState=state;
